### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by may210297** [fudan-zvg/DeMo#1]
https://github.com/fudan-zvg/DeMo/blob/9fc58438ace874063ce5320586c95df8fd653863/src/model/trainer_forecast.py#L69

Hello, could you tell me the function of `predict` above? Very thanks!

**Comment by Zbozhou** [comment]
Hello, this function is not useful for training or evaluation.

**Comment by may210297** [comment]
Thank you for your quick reply！
