### ISSUE TITLE
Training Time Issues

### ISSUE THREAD

**Issue by skylineo** [fudan-zvg/DeMo#2]
Excellent job! I'm considering using this as the baseline for my work. I currently only have two Nvidia RTX 3090 GPUs, and I wonder how long it will take to complete 60 rounds of training?

**Comment by Zbozhou** [comment]
Thanks. With the default settings, training 60 epochs on Nvidia RTX 3090 GPUs should take less than 9 hours. You can try it yourself, and PyTorch Lightning will show the estimated training time based on your settings at the beginning.

**Comment by skylineo** [comment]
Thank you for your helpful reply, really appreciate it!
