### ISSUE TITLE
Leaderboard on av2

### ISSUE THREAD

**Issue by WYD137** [fudan-zvg/DeMo#3]
I am very glad that your work has achieved state-of-the-art (SOTA) on the leaderboard. May I ask if the test results on leaderboard was inferred by the checkpoint provided by this repository?

**Comment by skylineo** [comment]
I have the same question. I noticed that the provided weights don't match the model, so I set the strict parameter to False. The results shown below are slightly worse than the reference value.
![image](https://github.com/user-attachments/assets/798c2deb-5a07-4ddb-a8d7-bd0ccffee7fe)

**Comment by Zbozhou** [comment]
Thanks. This checkpoint is what we trained a few days ago, not the checkpoint in the article.

> I am very glad that your work has achieved state-of-the-art (SOTA) on the leaderboard. May I ask if the test results on leaderboard was inferred by the checkpoint provided by this repository?

**Comment by Zbozhou** [comment]
> I have the same question. I noticed that the provided weights don't match the model, so I set the strict parameter to False. The results shown below are slightly worse than the reference value. ![image](https://private-user-images.githubusercontent.com/132658636/380009429-798c2deb-5a07-4ddb-a8d7-bd0ccffee7fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mjk5OTAsIm5iZiI6MTcyOTgyOTY5MCwicGF0aCI6Ii8xMzI2NTg2MzYvMzgwMDA5NDI5LTc5OGMyZGViLTVhMDctNGRkYi1hOGQ3LWJkMGNjZmZlZTdmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwNDE0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzMwMTMwYzA4YmViZjE0MzQ0NDczN2M4YzcyNjVmNzFkMmNjNjQ1NTUyZDgxNGE1N2QyOTAyMDIyYTYzMTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fzsXe67OHeL-a3LQTp3CvKoSF_yyfQ5fwlAEgYBBwkg)

Thanks. In fact, we have two versions of the model. 'DeMo' and 'DeMo' + 'RealMotion', the specific difference you can refer to here: https://github.com/fudan-zvg/DeMo?tab=readme-ov-file#-results-and-checkpoints

**Comment by WYD137** [comment]
> Thanks. This checkpoint is what we trained a few days ago, not the checkpoint in the article.
> 
> > I am very glad that your work has achieved state-of-the-art (SOTA) on the leaderboard. May I ask if the test results on leaderboard was inferred by the checkpoint provided by this repository?

Thanks for your reply! Will the checkpoints in the article be released? By what method can such a checkpoint be obtained through training?

**Comment by Zbozhou** [comment]
> > Thanks. This checkpoint is what we trained a few days ago, not the checkpoint in the article.
> > > I am very glad that your work has achieved state-of-the-art (SOTA) on the leaderboard. May I ask if the test results on leaderboard was inferred by the checkpoint provided by this repository?
> 
> Thanks for your reply! Will the checkpoints in the article be released? OR by what method can such a checkpoint be obtained through training?

Thanks. The checkpoint can be obtained using the same training method, with only minor fluctuations.

**Comment by Zbozhou** [comment]
> > Thanks. This checkpoint is what we trained a few days ago, not the checkpoint in the article.
> > > I am very glad that your work has achieved state-of-the-art (SOTA) on the leaderboard. May I ask if the test results on leaderboard was inferred by the checkpoint provided by this repository?
> 
> Thanks for your reply! Will the checkpoints in the article be released? OR by what method can such a checkpoint be obtained through training?

And you can use 'DeMo' + 'RealMotion' to get better performance, which use 'RealMotion' as the baseline of 'DeMo'.

**Comment by WYD137** [comment]
Thanks for help!
