### ISSUE TITLE
About scene agents traj

### ISSUE THREAD

**Issue by John122-art** [fudan-zvg/DeMo#6]
![image](https://github.com/user-attachments/assets/d15d2c23-3200-48c7-851f-93e897782280)
Hello, thank you for your work. I have a question I'd like to ask: Why do you predict the future trajectories of other agents before predicting the agent-target trajectory? At first, I thought it was necessary to incorporate the other agents' trajectories to predict the agent-target trajectory, but that is not the case.

**Comment by Zbozhou** [comment]
Hi, the prediction of other agents' trajectories is based on the baseline models [Forecast-MAE](https://github.com/jchengai/forecast-mae) and [MTR](https://github.com/sshaoshuai/MTR). While the prediction of other agents enhances the scene context features, it is not directly related to our model.

**Comment by John122-art** [comment]
Thanks for your rely!
